name: Test vault-action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Access Vault
        with:
          url: https://vault.tenzin.io
          method: jwt
          role: tenzin-io.test-actions-workflows
