name: Test GitHub actions workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [dev-k8s]
    steps:
      - uses: actions/checkout@v3
      - name: Display github.ref_name variable
        run: echo ${{ github.ref_name }}
